apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sanquote-dev.fullname" . }}-config
  labels:
    {{- include "sanquote-dev.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>{{ .Values.config.title }}</title></head>
    <body>
      <h1>{{ .Values.config.greeting }}</h1>
      <p>{{ .Values.config.message }}</p>
      <p>Pod name: $(HOSTNAME)</p>
    </body>
    </html>
